  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 463, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/custom/iptech_account_reporting/__init__.py", line 1, in <module>
    from . import models
  File "/opt/odoo/custom/iptech_account_reporting/models/__init__.py", line 3, in <module>
    from . import account_report_sales
  File "/opt/odoo/custom/iptech_account_reporting/models/account_report_sales.py", line 7
    	a0 = fields.Char(string="Factura")
    ^
TabError: inconsistent use of tabs and spaces in indentation
2024-05-24 10:36:19,517 265557 INFO odooiptech werkzeug: 181.225.81.219 - - [24/May/2024 10:36:19] "GET /favicon.ico HTTP/1.1" 500 - 11 0.008 0.239
2024-05-24 10:36:21,286 265551 INFO odooiptech odoo.modules.loading: loading 1 modules... 
2024-05-24 10:36:21,308 265551 INFO odooiptech odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries (+0 extra) 
2024-05-24 10:36:21,316 265551 WARNING odooiptech odoo.modules.module: Missing `license` key in manifest for 'iptech_chatter_extension', defaulting to LGPL-3 
2024-05-24 10:36:21,339 265551 WARNING odooiptech odoo.modules.module: Missing `license` key in manifest for 'iptech_account_reporting', defaulting to LGPL-3 
2024-05-24 10:36:21,383 265551 WARNING odooiptech odoo.modules.module: Missing `license` key in manifest for 'task_tab_products', defaulting to LGPL-3 
2024-05-24 10:36:21,384 265551 WARNING odooiptech odoo.modules.module: Missing `license` key in manifest for 'order_preview_extra', defaulting to LGPL-3 
2024-05-24 10:36:21,406 265551 WARNING odooiptech odoo.modules.module: Missing `license` key in manifest for 'iptech_prorateo', defaulting to LGPL-3 
2024-05-24 10:36:21,431 265551 INFO odooiptech odoo.modules.loading: loading 210 modules... 
2024-05-24 10:36:21,447 265551 WARNING odooiptech odoo.api.create: The model odoo.addons.generic_mixin.models.generic_mixin_uuid is not overriding the create method in batch 
2024-05-24 10:36:21,944 265551 WARNING odooiptech odoo.api.create: The model odoo.addons.generic_todo.models.generic_todo is not overriding the create method in batch 
2024-05-24 10:36:22,091 265551 WARNING odooiptech odoo.api.create: The model odoo.addons.generic_request_related_doc.models.request_related_document_type is not overriding the create method in batch 
2024-05-24 10:36:22,099 265551 WARNING odooiptech odoo.api.create: The model odoo.addons.generic_request_survey.models.survey_user_input is not overriding the create method in batch 
2024-05-24 10:36:22,580 265551 CRITICAL odooiptech odoo.modules.module: Couldn't load module iptech_account_reporting 
2024-05-24 10:36:22,580 265551 CRITICAL odooiptech odoo.modules.module: inconsistent use of tabs and spaces in indentation (account_report_sales.py, line 7) 
2024-05-24 10:36:22,582 265551 WARNING odooiptech odoo.modules.loading: Transient module states were reset 
2024-05-24 10:36:22,582 265551 ERROR odooiptech odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 64, in __new__
    return cls.registries[db_name]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'odooiptech'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 188, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 463, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/custom/iptech_account_reporting/__init__.py", line 1, in <module>
    from . import models
  File "/opt/odoo/custom/iptech_account_reporting/models/__init__.py", line 3, in <module>
    from . import account_report_sales
  File "/opt/odoo/custom/iptech_account_reporting/models/account_report_sales.py", line 7
    	a0 = fields.Char(string="Factura")
    ^
TabError: inconsistent use of tabs and spaces in indentation
2024-05-24 10:36:22,583 265551 ERROR odooiptech odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 64, in __new__
    return cls.registries[db_name]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'odooiptech'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1998, in __call__
    response = request._serve_db()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1563, in _serve_db
    self.registry = Registry(self.db).check_signaling()
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 66, in __new__
    return cls.new(db_name)
  File "<decorator-gen-14>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 188, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 463, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/custom/iptech_account_reporting/__init__.py", line 1, in <module>
    from . import models
  File "/opt/odoo/custom/iptech_account_reporting/models/__init__.py", line 3, in <module>
    from . import account_report_sales
  File "/opt/odoo/custom/iptech_account_reporting/models/account_report_sales.py", line 7
    	a0 = fields.Char(string="Factura")
    ^
TabError: inconsistent use of tabs and spaces in indentation
2024-05-24 10:36:22,585 265551 INFO odooiptech werkzeug: 181.225.81.219 - - [24/May/2024 10:36:22] "GET /service_worker.js HTTP/1.1" 500 - 11 0.013 1.306
